<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.16" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SilentHill.Domain\SilentHill.Domain.csproj" />
    <ProjectReference Include="..\SilentHill.Application\SilentHill.Application.csproj" />
  </ItemGroup>

</Project>
